#!/usr/bin/env python3
"""Export k-fold TCN compression aggregates into LaTeX table fragments.

Incomplete configs render as ``--- (N/15)`` placeholders until all 15 fold×seed runs exist.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

RESEARCH_ROOT = Path(__file__).resolve().parents[1]
sys_path = RESEARCH_ROOT
import sys

sys.path.insert(0, str(sys_path))

from experiments.compression.kfold_configs import (  # noqa: E402
    COMPRESSION_CONFIGS,
    FINETUNE_ABLATION_CONFIGS,
    PRIMARY_COMPRESSION_CONFIGS,
    finetune_epochs_for_config,
    normalize_config_label,
)

EXPECTED_RUNS = 15
TOTAL_JOBS = len(COMPRESSION_CONFIGS) * EXPECTED_RUNS


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def count_completed_runs(model: str = "tcn") -> dict[str, int]:
    root = RESEARCH_ROOT / "experiments" / "compression" / "runs" / model
    counts: dict[str, int] = {}
    for config in COMPRESSION_CONFIGS:
        counts[config] = len(list(root.glob(f"fold*_seed*/{config}/metrics.json")))
    return counts


def fmt_mean_std(entry: dict | None, *, n_complete: int) -> str:
    if entry is None or n_complete < EXPECTED_RUNS:
        return f"--- ({n_complete}/{EXPECTED_RUNS})"
    mean = entry.get("overall_mean")
    std = entry.get("overall_std")
    if mean is None or math.isnan(mean):
        return f"--- ({n_complete}/{EXPECTED_RUNS})"
    if std is None or math.isnan(std):
        return f"{mean * 100:.2f}"
    return f"{mean * 100:.2f}\\,$\\pm$\\,{std * 100:.2f}"


def fmt_wilcoxon(entry: dict | None, *, n_complete: int) -> str:
    if entry is None or n_complete < EXPECTED_RUNS:
        return "---"
    p = entry.get("wilcoxon_p")
    if p is None:
        return "---"
    if p < 0.001:
        return f"{p:.2e}"
    return f"{p:.3f}"


def display_config_label(config: str) -> str:
    base, ft = normalize_config_label(config)
    if ft is not None:
        return f"{base} ({ft} ep)"
    return base


def write_kfold_compression_table(
    path: Path,
    *,
    summary_path: Path,
    model: str = "tcn",
) -> None:
    summary = load_json(summary_path)
    comp = summary.get("compression", {}).get(model, {})
    configs = comp.get("configs", {})
    comparisons = comp.get("fp32_vs_compression", {})
    counts = count_completed_runs(model)
    total_jobs = sum(counts.values())

    lines = [
        "% Auto-generated by analysis/export_kfold_compression_tex.py",
        "% Re-run after: python analysis/aggregate_runs.py && python analysis/export_kfold_compression_tex.py",
        "\\begin{table}[!t]",
        "  \\centering",
        f"  \\caption{{TCN K-Fold Compression (Macro F1 \\%, Mean\\,$\\pm\\,$Std; $N{{=}}15$ per config)}}",
        "  \\label{tab:kfold-compression}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{4pt}",
        "  \\renewcommand{\\arraystretch}{1.08}",
        "  \\begin{tabular}{@{} l c @{\\hspace{8pt}} c @{\\hspace{4pt}} c @{}}",
        "    \\toprule",
        "    \\textbf{Config} & \\textbf{Macro F1} & \\textbf{PSw F1} & \\textbf{Wilcoxon $p$ vs.\\ FP32} \\\\",
        "    \\midrule",
    ]

    for config in PRIMARY_COMPRESSION_CONFIGS:
        cfg = configs.get(config, {})
        macro = cfg.get("macro_f1")
        psw = cfg.get("phase_f1", {}).get("PSw")
        n = counts.get(config, 0)
        wilcoxon = comparisons.get(config) if config != "FP32" else None
        p_cell = "---" if config == "FP32" else fmt_wilcoxon(wilcoxon, n_complete=n)
        label = display_config_label(config)
        lines.append(
            f"    {label} & {fmt_mean_std(macro, n_complete=n)} "
            f"& {fmt_mean_std(psw, n_complete=n)} & {p_cell} \\\\"
        )

    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "",
            f"  \\vspace{{0.5em}}",
        ]
    )
    if total_jobs >= TOTAL_JOBS:
        lines.append(
            f"  {{\\scriptsize Paired Wilcoxon signed-rank tests on matched fold$\\times$seed pairs "
            f"($N{{=}}15$) vs.\\ FP32. All configs complete ({total_jobs}/{TOTAL_JOBS} jobs). "
            f"$p{{=}}6.10\\mathrm{{e}}{{-05}}$ is the $N{{=}}15$ Wilcoxon floor (see Limitations). "
            f"Config names denote \\% channels retained; Prune25 is most aggressive, Prune75 "
            f"mildest.}}"
        )
    else:
        lines.append(
            f"  {{\\scriptsize Placeholder cells show completed runs out of $N{{=}}15$ per config. "
            f"Total compression jobs complete: {total_jobs}/{TOTAL_JOBS}.}}"
        )
    lines.extend(["\\end{table}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"Wrote {path} ({total_jobs}/{TOTAL_JOBS} jobs complete)")


def write_finetune_ablation_table(
    path: Path,
    *,
    summary_path: Path,
    model: str = "tcn",
) -> None:
    summary = load_json(summary_path)
    comp = summary.get("compression", {}).get(model, {})
    configs = comp.get("configs", {})
    comparisons = comp.get("fp32_vs_compression", {})
    counts = count_completed_runs(model)
    finetune_rows = ("Prune50",) + FINETUNE_ABLATION_CONFIGS
    fp32_mean = configs.get("FP32", {}).get("macro_f1", {}).get("overall_mean")

    lines = [
        "% Auto-generated by analysis/export_kfold_compression_tex.py",
        "\\begin{table}[!t]",
        "  \\centering",
        f"  \\caption{{Prune50 Fine-Tuning Schedule Ablation (K-Fold; $N{{=}}15$; Wilcoxon vs.\\ FP32)}}",
        "  \\label{tab:finetune-ablation}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{2.5pt}",
        "  \\renewcommand{\\arraystretch}{1.08}",
        "  \\begin{tabular}{@{} l c c c c c @{}}",
        "    \\toprule",
        "    \\textbf{Config} & \\textbf{FT ep.} & \\textbf{Macro F1} & \\textbf{$\\Delta$ vs.\\ FP32} & \\textbf{PSw F1} & \\textbf{$p$} \\\\",
        "    \\midrule",
    ]

    for config in finetune_rows:
        cfg = configs.get(config, {})
        macro = cfg.get("macro_f1")
        psw = cfg.get("phase_f1", {}).get("PSw")
        n = counts.get(config, 0)
        epochs = finetune_epochs_for_config(config)
        mean = macro.get("overall_mean") if macro else None
        if mean is not None and fp32_mean is not None:
            delta_cell = f"{(mean - fp32_mean) * 100:+.2f}"
        else:
            delta_cell = "---"
        wilcoxon = comparisons.get(config)
        p_cell = fmt_wilcoxon(wilcoxon, n_complete=n)
        lines.append(
            f"    {display_config_label(config)} & {epochs} "
            f"& {fmt_mean_std(macro, n_complete=n)} & {delta_cell} "
            f"& {fmt_mean_std(psw, n_complete=n)} & {p_cell} \\\\"
        )

    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"Wrote {path}")


def write_pareto_grid_table(
    path: Path,
    *,
    summary_path: Path,
    model: str = "tcn",
) -> None:
    """Extended Pareto grid (non-FP32 primary configs) with estimated payload size."""
    summary = load_json(summary_path)
    comp = summary.get("compression", {}).get(model, {})
    configs = comp.get("configs", {})
    counts = count_completed_runs(model)
    root = RESEARCH_ROOT / "experiments" / "compression" / "runs" / model

    lines = [
        "% Auto-generated by analysis/export_kfold_compression_tex.py",
        "\\begin{table}[!t]",
        "  \\centering",
        f"  \\caption{{Extended Compression Grid (K-Fold; size from first completed run per config)}}",
        "  \\label{tab:pareto-grid}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{2.5pt}",
        "  \\renewcommand{\\arraystretch}{1.08}",
        "  \\begin{tabular}{@{} l r r c c @{}}",
        "    \\toprule",
        "    \\textbf{Config} & \\textbf{Params} & \\textbf{KB} & \\textbf{Macro F1} & \\textbf{PSw F1} \\\\",
        "    \\midrule",
    ]

    for config in PRIMARY_COMPRESSION_CONFIGS:
        if config == "FP32":
            continue
        cfg = configs.get(config, {})
        macro = cfg.get("macro_f1")
        psw = cfg.get("phase_f1", {}).get("PSw")
        n = counts.get(config, 0)
        params_cell = "---"
        kb_cell = "---"
        sample = next(root.glob(f"fold*_seed*/{config}/metrics.json"), None)
        if sample is not None:
            metrics = load_json(sample)
            params_cell = f"{metrics.get('params', 0):,}"
            kb_cell = f"{metrics.get('size_kb', 0):.1f}"
        lines.append(
            f"    {display_config_label(config)} & {params_cell} & {kb_cell} "
            f"& {fmt_mean_std(macro, n_complete=n)} & {fmt_mean_std(psw, n_complete=n)} \\\\"
        )

    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"Wrote {path}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--summary",
        type=Path,
        default=RESEARCH_ROOT / "analysis" / "aggregated_runs.json",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=RESEARCH_ROOT / "paper" / "tables" / "kfold_compression.tex",
    )
    p.add_argument(
        "--finetune-out",
        type=Path,
        default=RESEARCH_ROOT / "paper" / "tables" / "ablation_finetune.tex",
    )
    p.add_argument(
        "--pareto-out",
        type=Path,
        default=RESEARCH_ROOT / "paper" / "tables" / "ablation_pareto.tex",
    )
    p.add_argument("--model", default="tcn")
    args = p.parse_args()
    write_kfold_compression_table(args.out, summary_path=args.summary, model=args.model)
    write_finetune_ablation_table(args.finetune_out, summary_path=args.summary, model=args.model)
    write_pareto_grid_table(args.pareto_out, summary_path=args.summary, model=args.model)


if __name__ == "__main__":
    main()
