#!/usr/bin/env python3
"""Export ablation summary JSON into LaTeX table fragments for the paper."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

RESEARCH_ROOT = Path(__file__).resolve().parents[1]


def fmt_pct(value: float | None) -> str:
    if value is None:
        return "---"
    return f"{value * 100:.2f}"


def write_finetune_table(path: Path, summary: dict) -> None:
    lines = [
        "% Auto-generated by analysis/export_ablation_tex.py",
        "\\begin{table}[!t]",
        "  \\centering",
        "  \\caption{Prune50 Fine-Tuning Schedule Ablation (Legacy Split, Macro F1 \\%)}",
        "  \\label{tab:finetune-ablation}",
        "  \\footnotesize",
        "  \\setlength{\\tabcolsep}{4pt}",
        "  \\renewcommand{\\arraystretch}{1.12}",
        "  \\begin{tabular}{@{} l c c c c @{}}",
        "    \\toprule",
        "    \\textbf{Model} & \\textbf{Config} & \\textbf{Epochs} & \\textbf{Macro F1} & \\textbf{PSw F1} \\\\",
        "    \\midrule",
    ]
    rows = summary["models"]["tcn"]["finetune_ablation"]
    for row in rows:
        lines.append(
            f"    TCN & {row['config']} & {row.get('finetune_epochs', '---')} "
            f"& {fmt_pct(row.get('macro_f1'))} & {fmt_pct(row.get('phase_f1', {}).get('PSw'))} \\\\"
        )
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def write_pareto_table(path: Path, summary: dict) -> None:
    lines = [
        "% Auto-generated by analysis/export_ablation_tex.py",
        "\\begin{table}[!t]",
        "  \\centering",
        "  \\caption{Extended Compression Grid: TCN (Legacy Split)}",
        "  \\label{tab:pareto-grid}",
        "  \\footnotesize",
        "  \\setlength{\\tabcolsep}{3pt}",
        "  \\renewcommand{\\arraystretch}{1.1}",
        "  \\begin{tabular}{@{} l l r r c c @{}}",
        "    \\toprule",
        "    \\textbf{Model} & \\textbf{Config} & \\textbf{Params} & \\textbf{KB} & \\textbf{Macro F1} & \\textbf{PSw F1} \\\\",
        "    \\midrule",
    ]
    points = sorted(summary["models"]["tcn"]["pareto_grid"]["points"], key=lambda p: p["size_kb"])
    for i, pt in enumerate(points):
        model_cell = "TCN" if i == 0 else ""
        lines.append(
            f"    {model_cell} & {pt['name']} & {pt['params']:,} & {pt['size_kb']:.1f} "
            f"& {fmt_pct(pt['macro_f1'])} & {fmt_pct(pt.get('phase_f1', {}).get('PSw'))} \\\\"
        )
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--summary",
        type=Path,
        default=RESEARCH_ROOT / "analysis" / "ablation_summary.json",
    )
    p.add_argument("--out-dir", type=Path, default=RESEARCH_ROOT / "paper" / "tables")
    args = p.parse_args()

    summary = json.loads(args.summary.read_text())
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_finetune_table(args.out_dir / "ablation_finetune.tex", summary)
    write_pareto_table(args.out_dir / "ablation_pareto.tex", summary)
    print(f"Wrote {args.out_dir}/ablation_{{finetune,pareto}}.tex")


if __name__ == "__main__":
    main()
